# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Page.create!( title: "Home Page",
# 							content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo lectus, aliquet et consectetur ut, elementum at urna. Curabitur dignissim aliquam sem vitae molestie. Maecenas interdum elit id sem faucibus pulvinar. Etiam sed nunc in turpis sollicitudin adipiscing. Aenean enim quam, scelerisque eget lacinia eu, luctus eget erat. Etiam ullamcorper ante eu iaculis mattis. Sed suscipit sem ut tincidunt egestas. Nunc tristique leo eu neque fringilla, nec aliquam nisl lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent augue mauris, laoreet nec tristique vitae, aliquet ac nibh. Vestibulum ut est eros. Duis tincidunt ipsum eros, a tincidunt arcu ullamcorper nec. Vivamus dictum augue a nunc dignissim suscipit. In eu nulla at elit venenatis rhoncus et in ipsum.

# Aliquam sit amet ante imperdiet, aliquam nisi sed, pharetra tellus. Morbi mollis turpis pretium felis ultrices, nec suscipit neque vulputate. Donec vitae viverra eros. Praesent lobortis nisl vel molestie viverra. Maecenas scelerisque libero ut diam convallis, vel eleifend augue ultricies. Donec semper bibendum tortor sed mollis. Etiam aliquet dolor quam, eu semper neque luctus eget. Ut id rutrum sem, nec dignissim magna. Mauris aliquet dignissim turpis ultrices sagittis. Morbi congue tortor vitae dui egestas tincidunt. Sed volutpat posuere mi, vitae tempor est ullamcorper nec.

# Maecenas eget vulputate massa. Vivamus venenatis enim ipsum. Maecenas ac scelerisque quam. Integer varius consectetur enim vitae pharetra. Nullam imperdiet porta elit. Nunc in tincidunt augue, vel semper turpis. In egestas, nunc et aliquet vulputate, urna lorem pretium risus, eget ullamcorper ante quam sit amet eros. Nunc sed elit purus. Donec dapibus tempus ante et semper. Donec viverra magna sed enim mollis aliquam.

# In iaculis hendrerit sapien quis dignissim. Nullam congue auctor velit, mattis consequat sem aliquet sit amet. Praesent fermentum ligula quis leo pulvinar, vel luctus nulla venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat gravida sem, nec fringilla ligula semper et. Vivamus non nisl tortor. Sed tristique diam ligula, vel tristique nunc convallis ut. Suspendisse pulvinar, dolor eu vehicula consequat, metus erat iaculis massa, quis posuere augue elit sed augue. Aliquam convallis dui eu ante lobortis, nec fermentum enim porta. Praesent vitae mattis sem, in lacinia velit. Cras vestibulum purus nec augue malesuada interdum. Donec ut massa porttitor lacus viverra interdum. Nulla non justo suscipit, malesuada magna eget, euismod nibh. Quisque non arcu sagittis, mollis purus nec, tincidunt ante. Nunc pellentesque enim quis dui faucibus euismod.

# Quisque ultricies eros nec metus tempor imperdiet. Duis tincidunt, turpis ut cursus ullamcorper, lectus felis porttitor neque, sit amet posuere diam purus nec sapien. Maecenas id imperdiet velit. Sed a tellus ut magna fringilla pulvinar quis tincidunt elit. Vivamus et turpis luctus, ultricies lorem sed, auctor mi. Quisque pharetra vel lacus et ornare. Vestibulum non posuere lacus, in ullamcorper erat. Donec enim sapien, volutpat eget auctor id, gravida nec lectus.",
# 							slug: "home-page")
# Page.create!( title: "About Page",
# 							content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo lectus, aliquet et consectetur ut, elementum at urna. Curabitur dignissim aliquam sem vitae molestie. Maecenas interdum elit id sem faucibus pulvinar. Etiam sed nunc in turpis sollicitudin adipiscing. Aenean enim quam, scelerisque eget lacinia eu, luctus eget erat. Etiam ullamcorper ante eu iaculis mattis. Sed suscipit sem ut tincidunt egestas. Nunc tristique leo eu neque fringilla, nec aliquam nisl lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent augue mauris, laoreet nec tristique vitae, aliquet ac nibh. Vestibulum ut est eros. Duis tincidunt ipsum eros, a tincidunt arcu ullamcorper nec. Vivamus dictum augue a nunc dignissim suscipit. In eu nulla at elit venenatis rhoncus et in ipsum.

# Aliquam sit amet ante imperdiet, aliquam nisi sed, pharetra tellus. Morbi mollis turpis pretium felis ultrices, nec suscipit neque vulputate. Donec vitae viverra eros. Praesent lobortis nisl vel molestie viverra. Maecenas scelerisque libero ut diam convallis, vel eleifend augue ultricies. Donec semper bibendum tortor sed mollis. Etiam aliquet dolor quam, eu semper neque luctus eget. Ut id rutrum sem, nec dignissim magna. Mauris aliquet dignissim turpis ultrices sagittis. Morbi congue tortor vitae dui egestas tincidunt. Sed volutpat posuere mi, vitae tempor est ullamcorper nec.

# Maecenas eget vulputate massa. Vivamus venenatis enim ipsum. Maecenas ac scelerisque quam. Integer varius consectetur enim vitae pharetra. Nullam imperdiet porta elit. Nunc in tincidunt augue, vel semper turpis. In egestas, nunc et aliquet vulputate, urna lorem pretium risus, eget ullamcorper ante quam sit amet eros. Nunc sed elit purus. Donec dapibus tempus ante et semper. Donec viverra magna sed enim mollis aliquam.

# In iaculis hendrerit sapien quis dignissim. Nullam congue auctor velit, mattis consequat sem aliquet sit amet. Praesent fermentum ligula quis leo pulvinar, vel luctus nulla venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat gravida sem, nec fringilla ligula semper et. Vivamus non nisl tortor. Sed tristique diam ligula, vel tristique nunc convallis ut. Suspendisse pulvinar, dolor eu vehicula consequat, metus erat iaculis massa, quis posuere augue elit sed augue. Aliquam convallis dui eu ante lobortis, nec fermentum enim porta. Praesent vitae mattis sem, in lacinia velit. Cras vestibulum purus nec augue malesuada interdum. Donec ut massa porttitor lacus viverra interdum. Nulla non justo suscipit, malesuada magna eget, euismod nibh. Quisque non arcu sagittis, mollis purus nec, tincidunt ante. Nunc pellentesque enim quis dui faucibus euismod.

# Quisque ultricies eros nec metus tempor imperdiet. Duis tincidunt, turpis ut cursus ullamcorper, lectus felis porttitor neque, sit amet posuere diam purus nec sapien. Maecenas id imperdiet velit. Sed a tellus ut magna fringilla pulvinar quis tincidunt elit. Vivamus et turpis luctus, ultricies lorem sed, auctor mi. Quisque pharetra vel lacus et ornare. Vestibulum non posuere lacus, in ullamcorper erat. Donec enim sapien, volutpat eget auctor id, gravida nec lectus.",
# 							slug: "about-page")

Post.create!( title: "First post",
							 slug: "rails-post", 
							 content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo lectus, aliquet et consectetur ut, elementum at urna. Curabitur dignissim aliquam sem vitae molestie. Maecenas interdum elit id sem faucibus pulvinar. Etiam sed nunc in turpis sollicitudin adipiscing. Aenean enim quam, scelerisque eget lacinia eu, luctus eget erat. Etiam ullamcorper ante eu iaculis mattis. Sed suscipit sem ut tincidunt egestas. Nunc tristique leo eu neque fringilla, nec aliquam nisl lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent augue mauris, laoreet nec tristique vitae, aliquet ac nibh. Vestibulum ut est eros. Duis tincidunt ipsum eros, a tincidunt arcu ullamcorper nec. Vivamus dictum augue a nunc dignissim suscipit. In eu nulla at elit venenatis rhoncus et in ipsum.
Aliquam sit amet ante imperdiet, aliquam nisi sed, pharetra tellus. Morbi mollis turpis pretium felis ultrices, nec suscipit neque vulputate. Donec vitae viverra eros. Praesent lobortis nisl vel molestie viverra. Maecenas scelerisque libero ut diam convallis, vel eleifend augue ultricies. Donec semper bibendum tortor sed mollis. Etiam aliquet dolor quam, eu semper neque luctus eget. Ut id rutrum sem, nec dignissim magna. Mauris aliquet dignissim turpis ultrices sagittis. Morbi congue tortor vitae dui egestas tincidunt. Sed volutpat posuere mi, vitae tempor est ullamcorper nec.
Maecenas eget vulputate massa. Vivamus venenatis enim ipsum. Maecenas ac scelerisque quam. Integer varius consectetur enim vitae pharetra. Nullam imperdiet porta elit. Nunc in tincidunt augue, vel semper turpis. In egestas, nunc et aliquet vulputate, urna lorem pretium risus, eget ullamcorper ante quam sit amet eros. Nunc sed elit purus. Donec dapibus tempus ante et semper. Donec viverra magna sed enim mollis aliquam.
In iaculis hendrerit sapien quis dignissim. Nullam congue auctor velit, mattis consequat sem aliquet sit amet. Praesent fermentum ligula quis leo pulvinar, vel luctus nulla venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat gravida sem, nec fringilla ligula semper et. Vivamus non nisl tortor. Sed tristique diam ligula, vel tristique nunc convallis ut. Suspendisse pulvinar, dolor eu vehicula consequat, metus erat iaculis massa, quis posuere augue elit sed augue. Aliquam convallis dui eu ante lobortis, nec fermentum enim porta. Praesent vitae mattis sem, in lacinia velit. Cras vestibulum purus nec augue malesuada interdum. Donec ut massa porttitor lacus viverra interdum. Nulla non justo suscipit, malesuada magna eget, euismod nibh. Quisque non arcu sagittis, mollis purus nec, tincidunt ante. Nunc pellentesque enim quis dui faucibus euismod.
Quisque ultricies eros nec metus tempor imperdiet. Duis tincidunt, turpis ut cursus ullamcorper, lectus felis porttitor neque, sit amet posuere diam purus nec sapien. Maecenas id imperdiet velit. Sed a tellus ut magna fringilla pulvinar quis tincidunt elit. Vivamus et turpis luctus, ultricies lorem sed, auctor mi. Quisque pharetra vel lacus et ornare. Vestibulum non posuere lacus, in ullamcorper erat. Donec enim sapien, volutpat eget auctor id, gravida nec lectus.",
							 blurb: "Sample text for a first post")
Post.create!( title: "Second post",
							 slug: "rails-post-2", 
							 content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla justo lectus, aliquet et consectetur ut, elementum at urna. Curabitur dignissim aliquam sem vitae molestie. Maecenas interdum elit id sem faucibus pulvinar. Etiam sed nunc in turpis sollicitudin adipiscing. Aenean enim quam, scelerisque eget lacinia eu, luctus eget erat. Etiam ullamcorper ante eu iaculis mattis. Sed suscipit sem ut tincidunt egestas. Nunc tristique leo eu neque fringilla, nec aliquam nisl lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent augue mauris, laoreet nec tristique vitae, aliquet ac nibh. Vestibulum ut est eros. Duis tincidunt ipsum eros, a tincidunt arcu ullamcorper nec. Vivamus dictum augue a nunc dignissim suscipit. In eu nulla at elit venenatis rhoncus et in ipsum.

Aliquam sit amet ante imperdiet, aliquam nisi sed, pharetra tellus. Morbi mollis turpis pretium felis ultrices, nec suscipit neque vulputate. Donec vitae viverra eros. Praesent lobortis nisl vel molestie viverra. Maecenas scelerisque libero ut diam convallis, vel eleifend augue ultricies. Donec semper bibendum tortor sed mollis. Etiam aliquet dolor quam, eu semper neque luctus eget. Ut id rutrum sem, nec dignissim magna. Mauris aliquet dignissim turpis ultrices sagittis. Morbi congue tortor vitae dui egestas tincidunt. Sed volutpat posuere mi, vitae tempor est ullamcorper nec.

Maecenas eget vulputate massa. Vivamus venenatis enim ipsum. Maecenas ac scelerisque quam. Integer varius consectetur enim vitae pharetra. Nullam imperdiet porta elit. Nunc in tincidunt augue, vel semper turpis. In egestas, nunc et aliquet vulputate, urna lorem pretium risus, eget ullamcorper ante quam sit amet eros. Nunc sed elit purus. Donec dapibus tempus ante et semper. Donec viverra magna sed enim mollis aliquam.

In iaculis hendrerit sapien quis dignissim. Nullam congue auctor velit, mattis consequat sem aliquet sit amet. Praesent fermentum ligula quis leo pulvinar, vel luctus nulla venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat gravida sem, nec fringilla ligula semper et. Vivamus non nisl tortor. Sed tristique diam ligula, vel tristique nunc convallis ut. Suspendisse pulvinar, dolor eu vehicula consequat, metus erat iaculis massa, quis posuere augue elit sed augue. Aliquam convallis dui eu ante lobortis, nec fermentum enim porta. Praesent vitae mattis sem, in lacinia velit. Cras vestibulum purus nec augue malesuada interdum. Donec ut massa porttitor lacus viverra interdum. Nulla non justo suscipit, malesuada magna eget, euismod nibh. Quisque non arcu sagittis, mollis purus nec, tincidunt ante. Nunc pellentesque enim quis dui faucibus euismod.

Quisque ultricies eros nec metus tempor imperdiet. Duis tincidunt, turpis ut cursus ullamcorper, lectus felis porttitor neque, sit amet posuere diam purus nec sapien. Maecenas id imperdiet velit. Sed a tellus ut magna fringilla pulvinar quis tincidunt elit. Vivamus et turpis luctus, ultricies lorem sed, auctor mi. Quisque pharetra vel lacus et ornare. Vestibulum non posuere lacus, in ullamcorper erat. Donec enim sapien, volutpat eget auctor id, gravida nec lectus.",
							 blurb: "Sample text for a second post")